/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * Professional Ice Truck Tracking System API
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLoginBody } from '../iceTruckTrackingAPI.schemas';

import { customInstance } from '../../../shared/lib/orvalMutator';

export const getDefault = () => {
  /**
   * @summary Health check
   */
  const getHealth = () => {
    return customInstance<void>({ url: `/health`, method: 'GET' });
  };
  /**
   * @summary User login
   */
  const postAuthLogin = (postAuthLoginBody: PostAuthLoginBody) => {
    return customInstance<void>({
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthLoginBody,
    });
  };
  return {};
};
