// orval.config.cjs (root)
/** @type {import('orval').Config} */
const { resolve } = require('node:path');

const ROOT = __dirname;

module.exports = {
  iceTruck: {
    // 1) ใช้สเปค OpenAPI จาก backend
    input: resolve(ROOT, 'backend/src/docs/openapi.yaml'),

    // 2) ตั้งค่าการ generate SDK สำหรับ Dashboard
    output: {
      // ไฟล์คลายเอนต์หลัก (ไม่ทับไฟล์โค้ดมือ)
      target: resolve(ROOT, 'dashboard/src/lib/apiClient.ts'),

      // โฟลเดอร์เก็บ type/model ที่แยกเป็นไฟล์ๆ
      schemas: resolve(ROOT, 'dashboard/src/types/api'),

      // สร้าง React Query hooks (รองรับ v5) + ใช้ fetch เป็น HTTP client
      client: 'react-query',
      httpClient: 'fetch',

      // เคลียร์โฟลเดอร์ก่อน gen และจัดรูปแบบโค้ดให้สวยงาม
      clean: true,
      prettier: true,

      // เปิด mock type สำหรับ MSW/Storybook/test
      mock: true,

      // เพิ่ม header เพื่อปิด ESLint บนไฟล์ที่ gen อัตโนมัติ
      override: {
        header: [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '/* ⚠️ Auto-generated by Orval — do not edit. See orval.config.cjs. */',
        ].join('\n'),
      },
    },

    // 3) Format อัตโนมัติหลัง gen
    hooks: {
      afterAllFilesWrite: ['prettier -w'],
    },
  },
};
