packages:
  - 'backend'
  - 'dashboard'
  - 'mobile-app'
  - 'sdk/*'

# Relax peer dependency enforcement and auto-install peers to improve local DX
strictPeerDependencies: false
autoInstallPeers: true
