/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1Stats200PerformanceRadarItem = {
  key: string;
  score: number;
  max: number;
};
