/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1TrucksOrder =
  (typeof GetApiV1TrucksOrder)[keyof typeof GetApiV1TrucksOrder];

export const GetApiV1TrucksOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
