/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1Trucks200Item = {
  createdAt: string;
  id: number;
  name: string;
  updatedAt: string;
};
