/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { GetApiV1TrucksSort } from './getApiV1TrucksSort';
import type { GetApiV1TrucksOrder } from './getApiV1TrucksOrder';

export type GetApiV1TrucksParams = {
  page?: number;
  limit?: number;
  sort?: GetApiV1TrucksSort;
  order?: GetApiV1TrucksOrder;
};
