/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1Alerts200Item = {
  id: number;
  level: string;
  message: string;
  /** @nullable */
  truckId?: number | null;
  createdAt: string;
};
