/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { GetApiV1StatsRange } from './getApiV1StatsRange';

export type GetApiV1StatsParams = {
  range?: GetApiV1StatsRange;
};
