/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1Stats200Summary = {
  activeTrucks: number;
  avgCargoTempC: number;
  onTimeRatePct: number;
  fuelEfficiencyKmPerL: number;
  deliveriesCompleted: number;
  anomalyIndex: number;
};
