/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { GetApiV1Stats200Summary } from './getApiV1Stats200Summary';
import type { GetApiV1Stats200RevenueSeriesItem } from './getApiV1Stats200RevenueSeriesItem';
import type { GetApiV1Stats200FleetSeriesItem } from './getApiV1Stats200FleetSeriesItem';
import type { GetApiV1Stats200AlertsSeriesItem } from './getApiV1Stats200AlertsSeriesItem';
import type { GetApiV1Stats200TempBucketsItem } from './getApiV1Stats200TempBucketsItem';
import type { GetApiV1Stats200PerformanceRadarItem } from './getApiV1Stats200PerformanceRadarItem';

export type GetApiV1Stats200 = {
  summary: GetApiV1Stats200Summary;
  revenueSeries: GetApiV1Stats200RevenueSeriesItem[];
  fleetSeries: GetApiV1Stats200FleetSeriesItem[];
  alertsSeries: GetApiV1Stats200AlertsSeriesItem[];
  tempBuckets: GetApiV1Stats200TempBucketsItem[];
  performanceRadar: GetApiV1Stats200PerformanceRadarItem[];
  lastCalc: string;
};
