/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1StatsRange =
  (typeof GetApiV1StatsRange)[keyof typeof GetApiV1StatsRange];

 
export const GetApiV1StatsRange = {
  '1h': '1h',
  '24h': '24h',
  '7d': '7d',
} as const;
