/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { GetApiV1TrucksSort } from './getApiV1TrucksSort';
import type { GetApiV1TrucksOrder } from './getApiV1TrucksOrder';

export type GetApiV1TrucksParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  sort?: GetApiV1TrucksSort;
  order?: GetApiV1TrucksOrder;
};
