/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1TrucksSort =
  (typeof GetApiV1TrucksSort)[keyof typeof GetApiV1TrucksSort];

export const GetApiV1TrucksSort = {
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
