/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1Alerts200Item = {
  createdAt: string;
  id: number;
  level: string;
  message: string;
  truckId?: number | null;
};
