version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_URL=/usr/src/app/data/database.sqlite
      - JWT_SECRET=ice-truck-tracking-super-secret-jwt-key-production
      - SALT_ROUNDS=12
      - CLIENT_URL=http://localhost:3000,http://localhost:8081
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/v1/health/livez', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /usr/src/app/logs

  # Development override
  api-dev:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_URL=./database.sqlite
      - JWT_SECRET=ice-truck-tracking-super-secret-jwt-key-2024
      - SALT_ROUNDS=12
      - CLIENT_URL=http://localhost:3000,http://localhost:8081,http://localhost:8082,http://localhost:8083
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - dev

networks:
  default:
    name: ice-truck-network