/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * Professional Ice Truck Tracking System API
 * OpenAPI spec version: 1.0.0
 */
export type PostAuthLoginBody = {
  username?: string;
  password?: string;
};
