apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-truck-api
  labels:
    app: ice-truck-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ice-truck-api
  template:
    metadata:
      labels:
        app: ice-truck-api
    spec:
      containers:
      - name: api
        image: ice-truck-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        livenessProbe:
          httpGet:
            path: /api/v1/health/livez
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health/readyz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ice-truck-api-service
spec:
  selector:
    app: ice-truck-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer