/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GetApiV1StatsParams, GetApiV1TrucksParams } from '../types/api';
import { faker } from '@faker-js/faker';
import { HttpResponse, delay, http } from 'msw';
import type {
  GetApiV1Alerts200Item,
  GetApiV1Health200,
  GetApiV1Stats200,
  GetApiV1Trucks200Item,
} from '../types/api';

export const getHealthz = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/healthz`, options);
};

export const getGetHealthzQueryKey = () => {
  return [`/healthz`] as const;
};

export const getGetHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthz>>> = ({
    signal,
  }) => getHealthz({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHealthzQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealthz>>
>;
export type GetHealthzQueryError = AxiosError<unknown>;

export const useGetHealthz = <
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetHealthzQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getReadyz = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/readyz`, options);
};

export const getGetReadyzQueryKey = () => {
  return [`/readyz`] as const;
};

export const getGetReadyzQueryOptions = <
  TData = Awaited<ReturnType<typeof getReadyz>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getReadyz>>, TError, TData>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReadyzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReadyz>>> = ({
    signal,
  }) => getReadyz({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReadyz>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetReadyzQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReadyz>>
>;
export type GetReadyzQueryError = AxiosError<unknown>;

export const useGetReadyz = <
  TData = Awaited<ReturnType<typeof getReadyz>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getReadyz>>, TError, TData>;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetReadyzQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getMetrics = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/metrics`, options);
};

export const getGetMetricsQueryKey = () => {
  return [`/metrics`] as const;
};

export const getGetMetricsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMetrics>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMetricsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetrics>>> = ({
    signal,
  }) => getMetrics({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMetricsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMetrics>>
>;
export type GetMetricsQueryError = AxiosError<unknown>;

export const useGetMetrics = <
  TData = Awaited<ReturnType<typeof getMetrics>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMetricsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary API health
 */
export const getApiV1Health = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1Health200>> => {
  return axios.get(`/api/v1/health`, options);
};

export const getGetApiV1HealthQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const getGetApiV1HealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Health>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({
    signal,
  }) => getApiV1Health({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1HealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Health>>
>;
export type GetApiV1HealthQueryError = AxiosError<unknown>;

/**
 * @summary API health
 */
export const useGetApiV1Health = <
  TData = Awaited<ReturnType<typeof getApiV1Health>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiV1HealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary List trucks
 */
export const getApiV1Trucks = (
  params?: GetApiV1TrucksParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1Trucks200Item[]>> => {
  return axios.get(`/api/v1/trucks`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiV1TrucksQueryKey = (params?: GetApiV1TrucksParams) => {
  return [`/api/v1/trucks`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1TrucksQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Trucks>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiV1TrucksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Trucks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TrucksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Trucks>>> = ({
    signal,
  }) => getApiV1Trucks(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Trucks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TrucksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Trucks>>
>;
export type GetApiV1TrucksQueryError = AxiosError<unknown>;

/**
 * @summary List trucks
 */
export const useGetApiV1Trucks = <
  TData = Awaited<ReturnType<typeof getApiV1Trucks>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiV1TrucksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Trucks>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiV1TrucksQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary List alerts
 */
export const getApiV1Alerts = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1Alerts200Item[]>> => {
  return axios.get(`/api/v1/alerts`, options);
};

export const getGetApiV1AlertsQueryKey = () => {
  return [`/api/v1/alerts`] as const;
};

export const getGetApiV1AlertsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Alerts>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1AlertsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Alerts>>> = ({
    signal,
  }) => getApiV1Alerts({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1AlertsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Alerts>>
>;
export type GetApiV1AlertsQueryError = AxiosError<unknown>;

/**
 * @summary List alerts
 */
export const useGetApiV1Alerts = <
  TData = Awaited<ReturnType<typeof getApiV1Alerts>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiV1AlertsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Dashboard KPI summary
 */
export const getApiV1Stats = (
  params?: GetApiV1StatsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1Stats200>> => {
  return axios.get(`/api/v1/stats`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiV1StatsQueryKey = (params?: GetApiV1StatsParams) => {
  return [`/api/v1/stats`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1StatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Stats>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiV1StatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Stats>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1StatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Stats>>> = ({
    signal,
  }) => getApiV1Stats(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Stats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1StatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Stats>>
>;
export type GetApiV1StatsQueryError = AxiosError<unknown>;

/**
 * @summary Dashboard KPI summary
 */
export const useGetApiV1Stats = <
  TData = Awaited<ReturnType<typeof getApiV1Stats>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiV1StatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Stats>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiV1StatsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary WebSocket telemetry endpoint (upgrade required)
 */
export const getApiV1Telemetry = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`/api/v1/telemetry`, options);
};

export const getGetApiV1TelemetryQueryKey = () => {
  return [`/api/v1/telemetry`] as const;
};

export const getGetApiV1TelemetryQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Telemetry>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TelemetryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1Telemetry>>
  > = ({ signal }) => getApiV1Telemetry({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TelemetryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Telemetry>>
>;
export type GetApiV1TelemetryQueryError = AxiosError<void>;

/**
 * @summary WebSocket telemetry endpoint (upgrade required)
 */
export const useGetApiV1Telemetry = <
  TData = Awaited<ReturnType<typeof getApiV1Telemetry>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiV1TelemetryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetApiV1HealthResponseMock = (
  overrideResponse: any = {},
): GetApiV1Health200 => ({ ok: faker.datatype.boolean(), ...overrideResponse });

export const getGetApiV1TrucksResponseMock = (
  overrideResponse: any = {},
): GetApiV1Trucks200Item[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    createdAt: faker.word.sample(),
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.word.sample(),
    updatedAt: faker.word.sample(),
    ...overrideResponse,
  }));

export const getGetApiV1AlertsResponseMock = (
  overrideResponse: any = {},
): GetApiV1Alerts200Item[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    createdAt: faker.word.sample(),
    id: faker.number.int({ min: undefined, max: undefined }),
    level: faker.word.sample(),
    message: faker.word.sample(),
    truckId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    ...overrideResponse,
  }));

export const getGetApiV1StatsResponseMock = (
  overrideResponse: any = {},
): GetApiV1Stats200 => ({
  alertsSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    critical: faker.number.int({ min: undefined, max: undefined }),
    info: faker.number.int({ min: undefined, max: undefined }),
    t: faker.word.sample(),
    warning: faker.number.int({ min: undefined, max: undefined }),
    ...overrideResponse,
  })),
  fleetSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    active: faker.number.int({ min: undefined, max: undefined }),
    efficiency: faker.number.int({ min: undefined, max: undefined }),
    t: faker.word.sample(),
    ...overrideResponse,
  })),
  lastCalc: faker.word.sample(),
  performanceRadar: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    key: faker.word.sample(),
    max: faker.number.int({ min: undefined, max: undefined }),
    score: faker.number.int({ min: undefined, max: undefined }),
    ...overrideResponse,
  })),
  revenueSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    t: faker.word.sample(),
    value: faker.number.int({ min: undefined, max: undefined }),
    ...overrideResponse,
  })),
  summary: {
    activeTrucks: faker.number.int({ min: undefined, max: undefined }),
    anomalyIndex: faker.number.int({ min: undefined, max: undefined }),
    avgCargoTempC: faker.number.int({ min: undefined, max: undefined }),
    deliveriesCompleted: faker.number.int({ min: undefined, max: undefined }),
    fuelEfficiencyKmPerL: faker.number.int({ min: undefined, max: undefined }),
    onTimeRatePct: faker.number.int({ min: undefined, max: undefined }),
    ...overrideResponse,
  },
  tempBuckets: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    label: faker.word.sample(),
    value: faker.number.int({ min: undefined, max: undefined }),
    ...overrideResponse,
  })),
  ...overrideResponse,
});

export const getGetHealthzMockHandler = () => {
  return http.get('*/healthz', async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getGetReadyzMockHandler = () => {
  return http.get('*/readyz', async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getGetMetricsMockHandler = () => {
  return http.get('*/metrics', async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getGetApiV1HealthMockHandler = (
  overrideResponse?: GetApiV1Health200,
) => {
  return http.get('*/api/v1/health', async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse ? overrideResponse : getGetApiV1HealthResponseMock(),
      ),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );
  });
};

export const getGetApiV1TrucksMockHandler = (
  overrideResponse?: GetApiV1Trucks200Item[],
) => {
  return http.get('*/api/v1/trucks', async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse ? overrideResponse : getGetApiV1TrucksResponseMock(),
      ),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );
  });
};

export const getGetApiV1AlertsMockHandler = (
  overrideResponse?: GetApiV1Alerts200Item[],
) => {
  return http.get('*/api/v1/alerts', async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse ? overrideResponse : getGetApiV1AlertsResponseMock(),
      ),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );
  });
};

export const getGetApiV1StatsMockHandler = (
  overrideResponse?: GetApiV1Stats200,
) => {
  return http.get('*/api/v1/stats', async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse ? overrideResponse : getGetApiV1StatsResponseMock(),
      ),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );
  });
};

export const getGetApiV1TelemetryMockHandler = () => {
  return http.get('*/api/v1/telemetry', async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};
export const getIceTruckTrackingAPIMock = () => [
  getGetHealthzMockHandler(),
  getGetReadyzMockHandler(),
  getGetMetricsMockHandler(),
  getGetApiV1HealthMockHandler(),
  getGetApiV1TrucksMockHandler(),
  getGetApiV1AlertsMockHandler(),
  getGetApiV1StatsMockHandler(),
  getGetApiV1TelemetryMockHandler(),
];
