/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Ice Truck Tracking API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GetApiV1StatsParams, GetApiV1TrucksParams } from '../types/api';

import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  GetApiV1Alerts200Item,
  GetApiV1Health200,
  GetApiV1Stats200,
  GetApiV1Trucks200Item,
} from '../types/api';

export type getHealthzResponse200 = {
  data: void;
  status: 200;
};

export type getHealthzResponseSuccess = getHealthzResponse200 & {
  headers: Headers;
};
export type getHealthzResponse = getHealthzResponseSuccess;

export const getGetHealthzUrl = () => {
  return `/healthz`;
};

export const getHealthz = async (
  options?: RequestInit,
): Promise<getHealthzResponse> => {
  const res = await fetch(getGetHealthzUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthzResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getHealthzResponse;
};

export const getGetHealthzQueryKey = () => {
  return [`/healthz`] as const;
};

export const getGetHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthz>>> = ({
    signal,
  }) => getHealthz({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHealthzQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealthz>>
>;
export type GetHealthzQueryError = unknown;

export function useGetHealthz<
  TData = Awaited<ReturnType<typeof getHealthz>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getHealthz>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHealthzQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type getReadyzResponse200 = {
  data: void;
  status: 200;
};

export type getReadyzResponseSuccess = getReadyzResponse200 & {
  headers: Headers;
};
export type getReadyzResponse = getReadyzResponseSuccess;

export const getGetReadyzUrl = () => {
  return `/readyz`;
};

export const getReadyz = async (
  options?: RequestInit,
): Promise<getReadyzResponse> => {
  const res = await fetch(getGetReadyzUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReadyzResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getReadyzResponse;
};

export const getGetReadyzQueryKey = () => {
  return [`/readyz`] as const;
};

export const getGetReadyzQueryOptions = <
  TData = Awaited<ReturnType<typeof getReadyz>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getReadyz>>, TError, TData>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReadyzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReadyz>>> = ({
    signal,
  }) => getReadyz({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReadyz>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetReadyzQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReadyz>>
>;
export type GetReadyzQueryError = unknown;

export function useGetReadyz<
  TData = Awaited<ReturnType<typeof getReadyz>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getReadyz>>, TError, TData>;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetReadyzQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type getMetricsResponse200 = {
  data: void;
  status: 200;
};

export type getMetricsResponseSuccess = getMetricsResponse200 & {
  headers: Headers;
};
export type getMetricsResponse = getMetricsResponseSuccess;

export const getGetMetricsUrl = () => {
  return `/metrics`;
};

export const getMetrics = async (
  options?: RequestInit,
): Promise<getMetricsResponse> => {
  const res = await fetch(getGetMetricsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMetricsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMetricsResponse;
};

export const getGetMetricsQueryKey = () => {
  return [`/metrics`] as const;
};

export const getGetMetricsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMetrics>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMetricsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetrics>>> = ({
    signal,
  }) => getMetrics({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMetricsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMetrics>>
>;
export type GetMetricsQueryError = unknown;

export function useGetMetrics<
  TData = Awaited<ReturnType<typeof getMetrics>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMetrics>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMetricsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary API health
 */
export type getApiV1HealthResponse200 = {
  data: GetApiV1Health200;
  status: 200;
};

export type getApiV1HealthResponseSuccess = getApiV1HealthResponse200 & {
  headers: Headers;
};
export type getApiV1HealthResponse = getApiV1HealthResponseSuccess;

export const getGetApiV1HealthUrl = () => {
  return `/api/v1/health`;
};

export const getApiV1Health = async (
  options?: RequestInit,
): Promise<getApiV1HealthResponse> => {
  const res = await fetch(getGetApiV1HealthUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1HealthResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1HealthResponse;
};

export const getGetApiV1HealthQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const getGetApiV1HealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Health>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({
    signal,
  }) => getApiV1Health({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1HealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Health>>
>;
export type GetApiV1HealthQueryError = unknown;

/**
 * @summary API health
 */

export function useGetApiV1Health<
  TData = Awaited<ReturnType<typeof getApiV1Health>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Health>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1HealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List trucks
 */
export type getApiV1TrucksResponse200 = {
  data: GetApiV1Trucks200Item[];
  status: 200;
};

export type getApiV1TrucksResponseSuccess = getApiV1TrucksResponse200 & {
  headers: Headers;
};
export type getApiV1TrucksResponse = getApiV1TrucksResponseSuccess;

export const getGetApiV1TrucksUrl = (params?: GetApiV1TrucksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/trucks?${stringifiedParams}`
    : `/api/v1/trucks`;
};

export const getApiV1Trucks = async (
  params?: GetApiV1TrucksParams,
  options?: RequestInit,
): Promise<getApiV1TrucksResponse> => {
  const res = await fetch(getGetApiV1TrucksUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1TrucksResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1TrucksResponse;
};

export const getGetApiV1TrucksQueryKey = (params?: GetApiV1TrucksParams) => {
  return [`/api/v1/trucks`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1TrucksQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Trucks>>,
  TError = unknown,
>(
  params?: GetApiV1TrucksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Trucks>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TrucksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Trucks>>> = ({
    signal,
  }) => getApiV1Trucks(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Trucks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TrucksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Trucks>>
>;
export type GetApiV1TrucksQueryError = unknown;

/**
 * @summary List trucks
 */

export function useGetApiV1Trucks<
  TData = Awaited<ReturnType<typeof getApiV1Trucks>>,
  TError = unknown,
>(
  params?: GetApiV1TrucksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Trucks>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TrucksQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List alerts
 */
export type getApiV1AlertsResponse200 = {
  data: GetApiV1Alerts200Item[];
  status: 200;
};

export type getApiV1AlertsResponseSuccess = getApiV1AlertsResponse200 & {
  headers: Headers;
};
export type getApiV1AlertsResponse = getApiV1AlertsResponseSuccess;

export const getGetApiV1AlertsUrl = () => {
  return `/api/v1/alerts`;
};

export const getApiV1Alerts = async (
  options?: RequestInit,
): Promise<getApiV1AlertsResponse> => {
  const res = await fetch(getGetApiV1AlertsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1AlertsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1AlertsResponse;
};

export const getGetApiV1AlertsQueryKey = () => {
  return [`/api/v1/alerts`] as const;
};

export const getGetApiV1AlertsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Alerts>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1AlertsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Alerts>>> = ({
    signal,
  }) => getApiV1Alerts({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1AlertsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Alerts>>
>;
export type GetApiV1AlertsQueryError = unknown;

/**
 * @summary List alerts
 */

export function useGetApiV1Alerts<
  TData = Awaited<ReturnType<typeof getApiV1Alerts>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Alerts>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1AlertsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Dashboard KPI summary
 */
export type getApiV1StatsResponse200 = {
  data: GetApiV1Stats200;
  status: 200;
};

export type getApiV1StatsResponseSuccess = getApiV1StatsResponse200 & {
  headers: Headers;
};
export type getApiV1StatsResponse = getApiV1StatsResponseSuccess;

export const getGetApiV1StatsUrl = (params?: GetApiV1StatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/stats?${stringifiedParams}`
    : `/api/v1/stats`;
};

export const getApiV1Stats = async (
  params?: GetApiV1StatsParams,
  options?: RequestInit,
): Promise<getApiV1StatsResponse> => {
  const res = await fetch(getGetApiV1StatsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1StatsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1StatsResponse;
};

export const getGetApiV1StatsQueryKey = (params?: GetApiV1StatsParams) => {
  return [`/api/v1/stats`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1StatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Stats>>,
  TError = unknown,
>(
  params?: GetApiV1StatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Stats>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1StatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Stats>>> = ({
    signal,
  }) => getApiV1Stats(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Stats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1StatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Stats>>
>;
export type GetApiV1StatsQueryError = unknown;

/**
 * @summary Dashboard KPI summary
 */

export function useGetApiV1Stats<
  TData = Awaited<ReturnType<typeof getApiV1Stats>>,
  TError = unknown,
>(
  params?: GetApiV1StatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1Stats>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1StatsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary WebSocket telemetry endpoint (upgrade required)
 */
export type getApiV1TelemetryResponse101 = {
  data: void;
  status: 101;
};
export type getApiV1TelemetryResponseError = getApiV1TelemetryResponse101 & {
  headers: Headers;
};

export type getApiV1TelemetryResponse = getApiV1TelemetryResponseError;

export const getGetApiV1TelemetryUrl = () => {
  return `/api/v1/telemetry`;
};

export const getApiV1Telemetry = async (
  options?: RequestInit,
): Promise<getApiV1TelemetryResponse> => {
  const res = await fetch(getGetApiV1TelemetryUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1TelemetryResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiV1TelemetryResponse;
};

export const getGetApiV1TelemetryQueryKey = () => {
  return [`/api/v1/telemetry`] as const;
};

export const getGetApiV1TelemetryQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Telemetry>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TelemetryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1Telemetry>>
  > = ({ signal }) => getApiV1Telemetry({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TelemetryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Telemetry>>
>;
export type GetApiV1TelemetryQueryError = void;

/**
 * @summary WebSocket telemetry endpoint (upgrade required)
 */

export function useGetApiV1Telemetry<
  TData = Awaited<ReturnType<typeof getApiV1Telemetry>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Telemetry>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TelemetryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetApiV1HealthResponseMock = (
  overrideResponse: Partial<GetApiV1Health200> = {},
): GetApiV1Health200 => ({ ok: faker.datatype.boolean(), ...overrideResponse });

export const getGetApiV1TrucksResponseMock = (): GetApiV1Trucks200Item[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    updatedAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getGetApiV1AlertsResponseMock = (): GetApiV1Alerts200Item[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    level: faker.string.alpha({ length: { min: 10, max: 20 } }),
    message: faker.string.alpha({ length: { min: 10, max: 20 } }),
    truckId: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getGetApiV1StatsResponseMock = (
  overrideResponse: Partial<GetApiV1Stats200> = {},
): GetApiV1Stats200 => ({
  summary: {
    activeTrucks: faker.number.int({ min: undefined, max: undefined }),
    avgCargoTempC: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    onTimeRatePct: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    fuelEfficiencyKmPerL: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    deliveriesCompleted: faker.number.int({ min: undefined, max: undefined }),
    anomalyIndex: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  },
  revenueSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    t: faker.string.alpha({ length: { min: 10, max: 20 } }),
    value: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  fleetSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    t: faker.string.alpha({ length: { min: 10, max: 20 } }),
    active: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    efficiency: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  alertsSeries: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    t: faker.string.alpha({ length: { min: 10, max: 20 } }),
    critical: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    warning: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    info: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  tempBuckets: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    label: faker.string.alpha({ length: { min: 10, max: 20 } }),
    value: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  performanceRadar: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    key: faker.string.alpha({ length: { min: 10, max: 20 } }),
    score: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    max: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  lastCalc: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetHealthzMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/healthz',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetReadyzMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/readyz',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetMetricsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/metrics',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetApiV1HealthMockHandler = (
  overrideResponse?:
    | GetApiV1Health200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetApiV1Health200> | GetApiV1Health200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/health',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiV1HealthResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetApiV1TrucksMockHandler = (
  overrideResponse?:
    | GetApiV1Trucks200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetApiV1Trucks200Item[]> | GetApiV1Trucks200Item[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/trucks',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiV1TrucksResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetApiV1AlertsMockHandler = (
  overrideResponse?:
    | GetApiV1Alerts200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetApiV1Alerts200Item[]> | GetApiV1Alerts200Item[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/alerts',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiV1AlertsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetApiV1StatsMockHandler = (
  overrideResponse?:
    | GetApiV1Stats200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetApiV1Stats200> | GetApiV1Stats200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/stats',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiV1StatsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetApiV1TelemetryMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/v1/telemetry',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getIceTruckTrackingAPIMock = () => [
  getGetHealthzMockHandler(),
  getGetReadyzMockHandler(),
  getGetMetricsMockHandler(),
  getGetApiV1HealthMockHandler(),
  getGetApiV1TrucksMockHandler(),
  getGetApiV1AlertsMockHandler(),
  getGetApiV1StatsMockHandler(),
  getGetApiV1TelemetryMockHandler(),
];
